# -*- coding: utf-8 -*-
"""LabTask2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CEG1ZEGFMRSeRh_kwKQWZtD0LkYLfy8t
"""



"""# Matplotlib

# Numphy

# List
"""

my_list = [1,2,3,4,5,6,7,8,9,10]
print(my_list)

list_sum = sum(my_list)
list_max = max(my_list)
list_min = min(my_list)
my_list.append(12)
my_list.pop()
my_list.sort
my_list.reverse()
print(my_list)

print("Sum:", list_sum)
print("Maximum:", list_max)
print("Minimum:", list_min)

"""Tuple"""

my_tuple = ("apple", "banana", "cherry", "date")
print(my_tuple)
print('third element is',my_tuple[2])
my_list = list(my_tuple)
my_list.append("orange")
my_list[1]='peach'
my_tuple = tuple(my_list)
print('modified tuple',my_tuple)

"""# Set"""

set1 = {1, 2, 3}
set2 = {3, 4, 5}
print(set1)
print(set2)
set1.add(6)
set1.add(7)
print("Updated Set 1:", set1)
union_set = set1.union(set2)
intersection_set = set1.intersection(set2)

print("Union:", union_set)
print("Intersection:", intersection_set)

"""# Dictionary"""

student_marks = {
    "Ali": 85,
    "Ali": 92,
    "Ali": 78,
    "Ali": 95,
    "Ali": 88
}

print(student_marks)

